apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: kpng
  name: kpng
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kpng
  template:
    metadata:
      labels:
        app: kpng
    spec:
      nodeSelector:
        kube-proxy: v2
      serviceAccountName: kube-proxy
      hostNetwork: true
      containers:
      - image: mcluseau/kpng
        name: kpng
        volumeMounts:
        - name: empty
          mountPath: /k8s
        args:
        - kube
        - to-api
        - --listen=unix:///k8s/proxy.sock
      - image: mcluseau/kpng
        name: kpng-nftables
        securityContext:
          capabilities:
           add:
           - NET_ADMIN
        volumeMounts:
        - name: empty
          mountPath: /k8s
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        command:
        - kube-proxy-nftables
        - --target=unix:///k8s/proxy.sock
        #- --v=2
        #- --dry-run
      volumes:
      - name: empty
        emptyDir: {}
      - name: modules
        hostPath:
          path: /lib/modules
