name: Security

on:
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - 'doc/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'

env:
  GO_VERSION: "1.19"

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@v0.0.8
        with:
          package: cmd/...
          skip-upload: true
          fail-on-vuln: false
          vulncheck-version: latest
          go-version: ${{ env.GO_VERSION }}

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: govulncheck-report.sarif

  dependency-review:
    name: dependency review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Dependency Review
        uses: actions/dependency-review-action@c090f4e553673e6e505ea70d6a95362ee12adb94 # v3.0.3
